from db.mongo_handler import load_mongo_data
from utils.completion_rate import completion_rate
from utils.make_graph import make_daily_completion_rate_graph
from utils.make_graph import make_parent_completion_rate_graph
from utils.make_graph import make_daily_completion_time_graph
from utils.make_graph import make_parent_completion_time_graph
from utils.make_graph import make_parent_completion_reward_graph
from utils.make_graph import make_daily_approval_time_graph
from utils.make_graph import make_parent_approval_time_graph


target_id = '2de604dc-68f7-45b7-ad0b-ad1a63a2fc0b'
result = make_daily_completion_rate_graph(target_id)
print(result)