name: Deploy to EC2 (quest_dashboard)

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            # EC2 내 프로젝트 디렉토리로 이동
            cd /home/ubuntu/quest_dashboard

            # 최신 코드 가져오기
            git pull origin main

            # 기존 컨테이너 정리
            docker stop quest_dashboard || true
            docker rm quest_dashboard || true
            docker rmi quest_dashboard:latest || true

            # Docker 이미지 빌드 및 실행
            docker build -t quest_dashboard .
            docker run -d --name quest_dashboard -p 8000:8000 --env-file .env quest_dashboard